<a href="https://colab.research.google.com/github/srujaan/dl_with_pytorch/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np


### Tensors Initialization

In [8]:
# Using directly from data
data = [[1, 2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [11]:
# From a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [14]:
#From another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones like: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random tensor: \n {x_rand} \n")

Ones like: 
 tensor([[1, 1],
        [1, 1]]) 

Random tensor: 
 tensor([[0.5011, 0.2012],
        [0.9167, 0.9935]]) 



In [19]:
# With random or constant values
shape = (2, 3, ) # shape is a tuple tensor dimension
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.5785, 0.8081, 0.4723],
        [0.2111, 0.8458, 0.3400]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



### Standard numpy slicing and indexing

In [21]:
tensor = torch.ones(4,4) # 4 rows and 4 columns
tensor[:, 1] = 0 # DND rows, but override column 1 with zeros
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 