<a href="https://colab.research.google.com/github/srujaan/DL-with-PyTorch/blob/master/tensor_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# random numbers to form a uniform distribution
import torch

In [2]:
val = torch.rand(4, dtype=torch.float16)
val

tensor([0.5317, 0.7798, 0.2090, 0.0723], dtype=torch.float16)

In [3]:
torch.rand_like(val, dtype=torch.float32)

tensor([0.6688, 0.7322, 0.9744, 0.7461])

In [4]:
randn = torch.randn(4)
randn

tensor([-0.2612, -1.5451, -0.4013, -1.0165])

In [5]:
randn.cos_()

tensor([0.9661, 0.0257, 0.9206, 0.5263])

In [6]:
val.mean()

tensor(0.3982, dtype=torch.float16)

In [7]:
randint = torch.randint(3, 6, (4,2), dtype=torch.float32)
randint

tensor([[3., 5.],
        [4., 5.],
        [4., 4.],
        [4., 3.]])

# Create Ops

In [9]:
# arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [10]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.quantize_per_tensor(randint, 0.1, 10, torch.quint8)

tensor([[3., 5.],
        [4., 5.],
        [4., 4.],
        [4., 3.]], size=(4, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

In [18]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
torch.complex(torch.tensor([1., 2, 3]), torch.tensor([4., 5, 6]))

tensor([1.+4.j, 2.+5.j, 3.+6.j])

# Indexing, Slicing, Joining, Mutating Ops

In [26]:
x = torch.randn(2,3)
torch.cat((x,x), 0)

tensor([[-0.4872,  0.9073, -0.6407],
        [-0.9005,  0.1668, -0.1901],
        [-0.4872,  0.9073, -0.6407],
        [-0.9005,  0.1668, -0.1901]])

In [29]:
torch.cat((x,x), 1)

tensor([[-0.4872,  0.9073, -0.6407, -0.4872,  0.9073, -0.6407],
        [-0.9005,  0.1668, -0.1901, -0.9005,  0.1668, -0.1901]])

In [30]:
torch.hstack((x,x))

tensor([[-0.4872,  0.9073, -0.6407, -0.4872,  0.9073, -0.6407],
        [-0.9005,  0.1668, -0.1901, -0.9005,  0.1668, -0.1901]])

In [32]:
a = torch.arange(4.)


tensor([0., 1., 2., 3.])

In [33]:
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [39]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))


tensor([0, 1, 2, 3])

In [47]:
y = torch.zeros(2, 1, 2, 1, 2)
z = torch.squeeze(y)
o = torch.squeeze(y, 1)
print(y.size())
print(z.size())
print(o.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 1, 2])


In [72]:
rand_val = torch.randn( 2, 3)
rand_val

tensor([[-0.9962,  1.3811, -1.1322],
        [-1.3230,  1.8599, -1.0018]])

In [77]:
torch.transpose(rand_val, 0, 1)

tensor([[-0.9962, -1.3230],
        [ 1.3811,  1.8599],
        [-1.1322, -1.0018]])

In [80]:
t1 = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(t1, 0))
print(torch.unsqueeze(t1, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
