<a href="https://colab.research.google.com/github/srujaan/DL-with-PyTorch/blob/master/tensor_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# random numbers to form a uniform distribution
import torch

In [2]:
val = torch.rand(4, dtype=torch.float16)
val

tensor([0.5317, 0.7798, 0.2090, 0.0723], dtype=torch.float16)

In [3]:
torch.rand_like(val, dtype=torch.float32)

tensor([0.6688, 0.7322, 0.9744, 0.7461])

In [4]:
randn = torch.randn(4)
randn

tensor([-0.2612, -1.5451, -0.4013, -1.0165])

In [5]:
randn.cos_()

tensor([0.9661, 0.0257, 0.9206, 0.5263])

In [6]:
val.mean()

tensor(0.3982, dtype=torch.float16)

In [7]:
randint = torch.randint(3, 6, (4,2), dtype=torch.float32)
randint

tensor([[3., 5.],
        [4., 5.],
        [4., 4.],
        [4., 3.]])

# Create Ops

In [9]:
# arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [10]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.quantize_per_tensor(randint, 0.1, 10, torch.quint8)

tensor([[3., 5.],
        [4., 5.],
        [4., 4.],
        [4., 3.]], size=(4, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

In [18]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
torch.complex(torch.tensor([1., 2, 3]), torch.tensor([4., 5, 6]))

tensor([1.+4.j, 2.+5.j, 3.+6.j])