<a href="https://colab.research.google.com/github/srujaan/DL-with-PyTorch/blob/master/tensor_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# random numbers to form a uniform distribution
import torch

In [20]:
val = torch.rand(4, dtype=torch.float16)
val

tensor([0.4561, 0.7979, 0.2607, 0.8745], dtype=torch.float16)

In [19]:
torch.rand_like(val, dtype=torch.float32)

tensor([0.9643, 0.9599, 0.0804, 0.7399])

In [30]:
randn = torch.randn(4)
randn

tensor([-0.5191, -0.2991,  0.6780,  0.2831])

In [32]:
randn.cos_()

tensor([0.8682, 0.9556, 0.7788, 0.9602])

In [25]:
val.mean()

tensor(0.5972, dtype=torch.float16)

In [37]:
randint = torch.randint(3, 6, (4,2), dtype=torch.float32)
randint

tensor([[4., 3.],
        [5., 4.],
        [4., 5.],
        [4., 3.]])