<a href="https://colab.research.google.com/github/srujaan/DL-with-PyTorch/blob/master/tensor_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# random numbers to form a uniform distribution
import torch

In [2]:
val = torch.rand(4, dtype=torch.float16)
val

tensor([0.1382, 0.8140, 0.9106, 0.1772], dtype=torch.float16)

In [3]:
torch.rand_like(val, dtype=torch.float32)

tensor([0.2763, 0.1247, 0.7684, 0.1597])

In [4]:
randn = torch.randn(4)
randn

tensor([ 0.0989, -0.3979, -0.5258,  2.4436])

In [5]:
randn.cos_()

tensor([ 0.9951,  0.9219,  0.8649, -0.7662])

In [6]:
val.mean()

tensor(0.5103, dtype=torch.float16)

In [7]:
randint = torch.randint(3, 6, (4,2), dtype=torch.float32)
randint

tensor([[5., 5.],
        [5., 5.],
        [4., 4.],
        [4., 4.]])

# Create Ops

In [8]:
# arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [9]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [10]:
torch.quantize_per_tensor(randint, 0.1, 10, torch.quint8)

tensor([[5., 5.],
        [5., 5.],
        [4., 4.],
        [4., 4.]], size=(4, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
torch.complex(torch.tensor([1., 2, 3]), torch.tensor([4., 5, 6]))

tensor([1.+4.j, 2.+5.j, 3.+6.j])

# Indexing, Slicing, Joining, Mutating Ops

In [13]:
x = torch.randn(2,3)
torch.cat((x,x), 0)

tensor([[-0.7429,  0.6710,  0.8884],
        [ 1.1195,  0.3199, -0.2783],
        [-0.7429,  0.6710,  0.8884],
        [ 1.1195,  0.3199, -0.2783]])

In [14]:
torch.cat((x,x), 1)

tensor([[-0.7429,  0.6710,  0.8884, -0.7429,  0.6710,  0.8884],
        [ 1.1195,  0.3199, -0.2783,  1.1195,  0.3199, -0.2783]])

In [15]:
torch.hstack((x,x))

tensor([[-0.7429,  0.6710,  0.8884, -0.7429,  0.6710,  0.8884],
        [ 1.1195,  0.3199, -0.2783,  1.1195,  0.3199, -0.2783]])

In [16]:
a = torch.arange(4.)


In [17]:
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [18]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))


tensor([0, 1, 2, 3])

In [19]:
y = torch.zeros(2, 1, 2, 1, 2)
z = torch.squeeze(y)
o = torch.squeeze(y, 1)
print(y.size())
print(z.size())
print(o.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 1, 2])


In [20]:
rand_val = torch.randn( 2, 3)
rand_val

tensor([[-0.3948,  1.3153,  1.2059],
        [-0.6404,  1.6134, -0.8916]])

In [21]:
torch.transpose(rand_val, 0, 1)

tensor([[-0.3948, -0.6404],
        [ 1.3153,  1.6134],
        [ 1.2059, -0.8916]])

In [22]:
t1 = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(t1, 0))
print(torch.unsqueeze(t1, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [24]:
second_point = points[1]
second_point.storage_offset()

2

In [25]:
points.stride()

(2, 1)

In [26]:
points1 = points.clone().detach()
points1

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points1_t = points.t()
points1_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [28]:
# to verify two tensors share the same storage
id(points1.storage()) == id(points1_t.storage())

True

In [29]:
points1.stride()

(2, 1)

In [30]:
points1_t.stride()

(1, 2)

In [31]:
#some_t = torch.ones(3, 4, 5)
transpose_t = torch.transpose(some_t, 0, 2)
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [32]:
print(transpose_t.shape)
transpose_t

torch.Size([5, 4, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [33]:
a_list = torch.arange(9)
print(a_list.size())
print(a_list.storage_offset())
a_list.stride()

torch.Size([9])
0


(1,)

In [34]:
x = torch.tensor([
        [1,2,3],
        [4,5,6]
])

In [35]:
x.shape

torch.Size([2, 3])

In [36]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [37]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [38]:
y = torch.tensor([
      [
       [1,2,3],
       [4,5,6]
      ],
      [
       [1,2,3],
       [4,5,6]
      ],
      [
       [1,2,3],
       [4,5,6]
      ]
])

In [39]:
y.shape

torch.Size([3, 2, 3])

In [40]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [41]:
torch.sum(y, dim=1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [42]:
torch.sum(y, dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

In [43]:
z = torch.randint(4, (3,4,5))
z

tensor([[[3, 3, 3, 2, 1],
         [3, 0, 2, 3, 2],
         [2, 2, 0, 0, 0],
         [0, 1, 3, 3, 3]],

        [[0, 0, 2, 0, 1],
         [3, 0, 3, 1, 1],
         [1, 3, 3, 2, 3],
         [1, 0, 3, 2, 3]],

        [[3, 1, 1, 3, 0],
         [2, 0, 0, 3, 3],
         [3, 2, 1, 3, 3],
         [2, 3, 0, 1, 2]]])

In [44]:
torch.sum(z, dim=0)

tensor([[6, 4, 6, 5, 2],
        [8, 0, 5, 7, 6],
        [6, 7, 4, 5, 6],
        [3, 4, 6, 6, 8]])

In [45]:
torch.sum(z, dim=1)

tensor([[ 8,  6,  8,  8,  6],
        [ 5,  3, 11,  5,  8],
        [10,  6,  2, 10,  8]])

In [46]:
torch.sum(z, dim=2)

tensor([[12, 10,  4, 10],
        [ 3,  8, 12,  9],
        [ 8,  8, 12,  8]])

In [47]:
e = torch.randint(5, (3,3,3))
e

tensor([[[1, 4, 1],
         [1, 1, 2],
         [0, 1, 1]],

        [[0, 1, 0],
         [0, 1, 3],
         [4, 0, 3]],

        [[1, 2, 2],
         [0, 0, 2],
         [4, 3, 1]]])

In [48]:
torch.sum(e, dim=0)

tensor([[2, 7, 3],
        [1, 2, 7],
        [8, 4, 5]])

In [49]:
torch.sum(e, dim=1)

tensor([[2, 6, 4],
        [4, 2, 6],
        [5, 5, 5]])

In [51]:
torch.sum(e, dim=2)

tensor([[6, 4, 2],
        [1, 4, 7],
        [5, 2, 8]])

# Stride and  Storage 

In [53]:
t2 = torch.arange(12).view((3,4))
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [54]:
storage = t2.storage()
storage

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.LongStorage of size 12]

In [55]:
stride = t2.stride()
stride

(4, 1)

In [62]:
idx = (2,1)
item = t2[idx].item()
item

9

###### Now, using idx together with stride, we can access the item directly from the storage, like this:

In [65]:
loc = idx[0] * stride[0] + idx[1] * stride[1]
loc

9

In [69]:
# with 3d tensor
t3 = torch.rand(1200).view((10, 30, 4))
storage = t3.storage()
stride = t3.stride()
stride

(120, 4, 1)

In [71]:
idx = (4, 23, 2)
item = t3[idx].item()
item

0.8527129888534546

In [83]:
t4 = torch.randint(20, (2 ,3, 5, 5))
t4

tensor([[[[19,  9, 16, 10, 13],
          [ 1, 11, 16,  7, 14],
          [15,  0,  5, 12,  3],
          [ 4, 16,  5, 13, 16],
          [17,  5, 15,  7, 13]],

         [[ 2,  8, 18, 16, 11],
          [ 5, 10, 15,  4,  9],
          [ 6,  8, 18,  3, 16],
          [ 9, 19,  0, 12,  7],
          [12,  2, 17, 16,  6]],

         [[ 9, 18, 19,  6, 13],
          [ 8,  5, 11,  1,  9],
          [ 5,  6,  9, 10,  7],
          [15,  4, 10, 12,  7],
          [19,  4,  2, 12,  5]]],


        [[[ 3,  4, 10,  4, 14],
          [12,  1, 15, 15,  9],
          [18,  7,  7, 11, 12],
          [12,  7, 10,  0, 19],
          [15,  4,  8, 11,  7]],

         [[ 6, 16, 15,  7,  8],
          [ 5, 12,  5, 19,  6],
          [ 4,  6,  0,  3, 10],
          [10,  8, 17,  1, 15],
          [10, 18, 12,  2, 16]],

         [[ 0,  2, 19,  6, 18],
          [ 4, 14, 14, 18,  6],
          [18, 12,  8,  9, 19],
          [ 8, 18, 18,  3,  3],
          [ 8, 15,  8,  3, 17]]]])

In [94]:
t4.sum(dim=-1)

tensor([[[67, 49, 35, 54, 57],
         [55, 43, 51, 47, 53],
         [65, 34, 37, 48, 42]],

        [[35, 52, 55, 48, 45],
         [52, 47, 23, 51, 58],
         [45, 56, 66, 50, 51]]])