<a href="https://colab.research.google.com/github/srujaan/DL-with-PyTorch/blob/master/tensor_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# random numbers to form a uniform distribution
import torch

In [3]:
val = torch.rand(4, dtype=torch.float16)
val

tensor([0.1460, 0.4731, 0.7900, 0.3320], dtype=torch.float16)

In [4]:
torch.rand_like(val, dtype=torch.float32)

tensor([0.0090, 0.8767, 0.7591, 0.3185])

In [5]:
randn = torch.randn(4)
randn

tensor([ 2.5006, -0.3045, -0.3631,  0.2807])

In [6]:
randn.cos_()

tensor([-0.8015,  0.9540,  0.9348,  0.9609])

In [7]:
val.mean()

tensor(0.4353, dtype=torch.float16)

In [8]:
randint = torch.randint(3, 6, (4,2), dtype=torch.float32)
randint

tensor([[3., 3.],
        [5., 4.],
        [3., 5.],
        [3., 5.]])

# Create Ops

In [9]:
# arange
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [10]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [11]:
torch.quantize_per_tensor(randint, 0.1, 10, torch.quint8)

tensor([[3., 3.],
        [5., 4.],
        [3., 5.],
        [3., 5.]], size=(4, 2), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.complex(torch.tensor([1., 2, 3]), torch.tensor([4., 5, 6]))

tensor([1.+4.j, 2.+5.j, 3.+6.j])

# Indexing, Slicing, Joining, Mutating Ops

In [14]:
x = torch.randn(2,3)
torch.cat((x,x), 0)

tensor([[-1.4934, -0.0211, -0.6101],
        [ 1.4658, -0.1114, -0.1664],
        [-1.4934, -0.0211, -0.6101],
        [ 1.4658, -0.1114, -0.1664]])

In [15]:
torch.cat((x,x), 1)

tensor([[-1.4934, -0.0211, -0.6101, -1.4934, -0.0211, -0.6101],
        [ 1.4658, -0.1114, -0.1664,  1.4658, -0.1114, -0.1664]])

In [16]:
torch.hstack((x,x))

tensor([[-1.4934, -0.0211, -0.6101, -1.4934, -0.0211, -0.6101],
        [ 1.4658, -0.1114, -0.1664,  1.4658, -0.1114, -0.1664]])

In [17]:
a = torch.arange(4.)


In [18]:
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [19]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))


tensor([0, 1, 2, 3])

In [20]:
y = torch.zeros(2, 1, 2, 1, 2)
z = torch.squeeze(y)
o = torch.squeeze(y, 1)
print(y.size())
print(z.size())
print(o.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 1, 2])


In [21]:
rand_val = torch.randn( 2, 3)
rand_val

tensor([[-1.1600,  0.9023,  2.2693],
        [-0.4826,  0.2631, -0.0201]])

In [22]:
torch.transpose(rand_val, 0, 1)

tensor([[-1.1600, -0.4826],
        [ 0.9023,  0.2631],
        [ 2.2693, -0.0201]])

In [23]:
t1 = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(t1, 0))
print(torch.unsqueeze(t1, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [25]:
second_point = points[1]
second_point.storage_offset()

2

In [26]:
points.stride()

(2, 1)

In [27]:
points1 = points.clone().detach()
points1

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
points1_t = points.t()
points1_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [29]:
# to verify two tensors share the same storage
id(points1.storage()) == id(points1_t.storage())

True

In [30]:
points1.stride()

(2, 1)

In [31]:
points1_t.stride()

(1, 2)

In [33]:
some_t = torch.ones(3, 4, 5)
transpose_t = torch.transpose(some_t, 0, 2)
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [34]:
print(transpose_t.shape)
transpose_t

torch.Size([5, 4, 3])


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [35]:
a_list = torch.arange(9)
print(a_list.size())
print(a_list.storage_offset())
a_list.stride()

torch.Size([9])
0


(1,)

In [36]:
x = torch.tensor([
        [1,2,3],
        [4,5,6]
])

In [37]:
x.shape

torch.Size([2, 3])

In [38]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [39]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [40]:
y = torch.tensor([
      [
       [1,2,3],
       [4,5,6]
      ],
      [
       [1,2,3],
       [4,5,6]
      ],
      [
       [1,2,3],
       [4,5,6]
      ]
])

In [41]:
y.shape

torch.Size([3, 2, 3])

In [42]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [43]:
torch.sum(y, dim=1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [44]:
torch.sum(y, dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

In [45]:
z = torch.randint(4, (3,4,5))
z

tensor([[[3, 0, 2, 1, 1],
         [0, 0, 2, 2, 0],
         [2, 2, 1, 1, 1],
         [0, 0, 2, 0, 0]],

        [[0, 2, 3, 0, 2],
         [1, 3, 2, 3, 1],
         [2, 3, 1, 0, 0],
         [3, 2, 1, 1, 1]],

        [[2, 0, 3, 2, 0],
         [0, 0, 2, 2, 2],
         [0, 0, 2, 2, 3],
         [2, 1, 1, 2, 0]]])

In [46]:
torch.sum(z, dim=0)

tensor([[5, 2, 8, 3, 3],
        [1, 3, 6, 7, 3],
        [4, 5, 4, 3, 4],
        [5, 3, 4, 3, 1]])

In [47]:
torch.sum(z, dim=1)

tensor([[ 5,  2,  7,  4,  2],
        [ 6, 10,  7,  4,  4],
        [ 4,  1,  8,  8,  5]])

In [48]:
torch.sum(z, dim=2)

tensor([[ 7,  4,  7,  2],
        [ 7, 10,  6,  8],
        [ 7,  6,  7,  6]])

In [49]:
e = torch.randint(5, (3,3,3))
e

tensor([[[3, 1, 2],
         [4, 1, 0],
         [1, 0, 3]],

        [[4, 1, 4],
         [2, 4, 4],
         [4, 2, 3]],

        [[1, 2, 2],
         [2, 1, 1],
         [4, 4, 3]]])

In [50]:
torch.sum(e, dim=0)

tensor([[8, 4, 8],
        [8, 6, 5],
        [9, 6, 9]])

In [51]:
torch.sum(e, dim=1)

tensor([[ 8,  2,  5],
        [10,  7, 11],
        [ 7,  7,  6]])

In [52]:
torch.sum(e, dim=2)

tensor([[ 6,  5,  4],
        [ 9, 10,  9],
        [ 5,  4, 11]])

# Stride and  Storage 

In [53]:
t2 = torch.arange(12).view((3,4))
t2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [54]:
storage = t2.storage()
storage

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.LongStorage of size 12]

In [55]:
stride = t2.stride()
stride

(4, 1)

In [56]:
idx = (2,1)
item = t2[idx].item()
item

9

###### Now, using idx together with stride, we can access the item directly from the storage, like this:

In [57]:
loc = idx[0] * stride[0] + idx[1] * stride[1]
loc

9

In [58]:
# with 3d tensor
t3 = torch.rand(1200).view((10, 30, 4))
storage = t3.storage()
stride = t3.stride()
stride

(120, 4, 1)

In [59]:
idx = (4, 23, 2)
item = t3[idx].item()
item

0.9091154932975769

In [60]:
t4 = torch.randint(20, (2 ,3, 5, 5))
t4

tensor([[[[19, 16, 11,  3,  3],
          [11, 18,  0, 19, 18],
          [ 7, 10,  5, 12,  1],
          [15,  8, 14, 11, 10],
          [11,  5,  5, 13, 16]],

         [[14, 13, 13, 19,  3],
          [ 3,  6,  3, 15,  0],
          [ 0, 15, 17, 19,  1],
          [ 4, 19, 13,  8,  2],
          [10, 17,  8, 13,  3]],

         [[ 9, 10, 17,  9, 14],
          [ 7, 17,  0,  7, 17],
          [ 4, 13,  8,  3, 15],
          [ 1,  8, 16, 10,  6],
          [17,  8,  2, 15,  6]]],


        [[[18,  1, 11, 16,  7],
          [ 8, 16,  7,  0,  1],
          [16,  6,  1, 12,  0],
          [ 4,  7,  7, 14, 15],
          [ 8,  0, 12, 16, 15]],

         [[ 2, 10,  6, 14,  0],
          [ 3,  1, 17,  3,  4],
          [18, 17,  5, 11, 17],
          [ 1, 15,  6,  2, 13],
          [ 8,  8, 18,  9, 14]],

         [[ 9, 14,  5, 17,  5],
          [13,  7, 13, 12, 16],
          [18, 11,  4,  8,  3],
          [ 8,  4, 16, 16,  9],
          [ 4, 18,  1,  9,  0]]]])

In [61]:
t4.sum(dim=-1)

tensor([[[52, 66, 35, 58, 50],
         [62, 27, 52, 46, 51],
         [59, 48, 43, 41, 48]],

        [[53, 32, 35, 47, 51],
         [32, 28, 68, 37, 57],
         [50, 61, 44, 53, 32]]])

In [62]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points[2]
points_storage.storage_offset()


4

In [63]:
t4 = torch.randint(7,(3,2), dtype=torch.float32)
t4

tensor([[6., 5.],
        [5., 3.],
        [3., 6.]])

In [64]:
points_t4 = t4.t()
points_t4

tensor([[6., 5., 3.],
        [5., 3., 6.]])

In [65]:
t4.storage()

 6.0
 5.0
 5.0
 3.0
 3.0
 6.0
[torch.FloatStorage of size 6]

In [66]:
t4.stride()

(2, 1)

In [67]:
points_t4.stride()

(1, 2)

In [68]:
some_t5 = torch.ones(3, 4, 5)
some_t5

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [69]:
# to transpose without changing the dimesions use (-1, 1)
some_t5.transpose(-1,1).shape 


torch.Size([3, 5, 4])

In [70]:
# We can transpose a multidimensional array by specifying the two
# dimensions along which transposing (flipping shape and stride) should occur:
print(some_t5.transpose(0,2).shape)
print(some_t5.transpose(0,2))

torch.Size([5, 4, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


### Contiguous tensors

In [71]:
points1.is_contiguous()
points1_t_cont = points1_t.contiguous()
print(points1_t_cont)
print(points1_t_cont.is_contiguous())

tensor([[4., 5., 2.],
        [1., 3., 1.]])
True


In [104]:
t6 = torch.arange(9, dtype=torch.float32)
print(t6.size())
print(t6.storage_offset())
print(t6.stride())
t6

torch.Size([9])
0
(1,)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [105]:
b = t6.view(3, 3)
b

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [106]:
id(t6.storage()) == id(b.storage())

True

In [107]:
c = b[1:, 1:]
print(c)
print(c.shape)
print(c.storage_offset())
print(c.stride())

tensor([[4., 5.],
        [7., 8.]])
torch.Size([2, 2])
4
(3, 1)


In [108]:
torch.cos_(t6)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [109]:
t6

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])