### Python list


In [2]:
a = [23, 43, 94]
a[0], a[1]

(23, 43)

In [4]:
a[2] = 45
a

[23, 43, 45]

# Tensors

In [6]:
import torch


In [7]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [9]:
a[1] = 3
a

tensor([1., 3., 1.])

In [11]:
a[1] = float(a[1])
a

tensor([1., 3., 1.])

In [12]:
float(a[2])

1.0

In [13]:
# Tensor are contiguous memory blocks containing unboxed C numeric
# types rather than Python objects. Each element is a 32-bit

In [14]:
points = torch.zeros(6) # Array size of 6
# Overwrite zero values
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
# Other way of creating tensors
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 10])
points2

tensor([ 4.,  1.,  5.,  3.,  2., 10.])

In [20]:
points2[2] = 6
points2

tensor([ 4.,  1.,  6.,  3.,  2., 10.])

In [28]:
# for example to get coordinates of first two points
x1y1 = float(points2[0]), float(points2[1])
# type(x1y1) -> tuple
x1y1

(4.0, 1.0)

In [31]:
# 2D tensor
points3 = torch.tensor([[1.0, 4.0], [5.0, 3.0], [2.0, 1.0]])
points3

tensor([[1., 4.],
        [5., 3.],
        [2., 1.]])

In [34]:
points3[1][0]

tensor(5.)

In [36]:
points3.shape

torch.Size([3, 2])

In [40]:
# Instantiate the tensor shape of zeros using tuple
points4 = torch.zeros(3,3)
# Rewrite the points4 of zeros to a tensor of values
points4 = torch.tensor([[4.0, 5.0, 6.0], [1.0, 3.0, 9.0], [7.0, 2.0, 4.0]])
# display points4 values
points4

tensor([[4., 5., 6.],
        [1., 3., 9.],
        [7., 2., 4.]])

In [49]:
# Get the value in points4
# Similar to points[0][1] yields the same answer
points4[0, 1]


tensor(5.)